In [4]:
import numpy as np

## 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [5]:
arr = np.linspace(1,10, num=10,dtype=int)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


## 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


In [6]:
matrix = np.zeros((3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.


In [7]:
matrix_5x5 = np.random.randint(1, 10, size=(5,5))
print(matrix_5x5)

[[8 2 6 9 2]
 [4 9 4 3 5]
 [9 2 7 4 8]
 [3 4 7 2 1]
 [4 7 3 4 9]]


## 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.


In [8]:
matrix_4x4 = np.random.random((4,4))
print(matrix_4x4)

[[0.09905665 0.38290801 0.97297346 0.6701146 ]
 [0.94078315 0.80513317 0.20044792 0.26298101]
 [0.42283495 0.10152455 0.68940696 0.7300893 ]
 [0.85204926 0.83634373 0.83559122 0.86847866]]


## 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [9]:
m5_1 = np.random.randint(1, 10, size=(5,5))
m5_2 = np.random.randint(1, 10, size=(5,5))
mm_sum = m5_1 + m5_2
mm_diff = m5_1 - m5_2
mm_prod = m5_1 * m5_2
print(f"first matrix: \n{m5_1}\n")
print(f"second matrix: \n{m5_2}\n")
print(f"sum:  \n{mm_sum}\n")
print(f"diff:  \n{mm_diff}\n")
print(f"prod:  \n{mm_prod}")

first matrix: 
[[8 2 8 9 5]
 [9 9 6 6 3]
 [1 6 6 9 4]
 [7 5 5 8 2]
 [1 8 6 6 8]]

second matrix: 
[[1 3 7 3 2]
 [6 8 2 5 3]
 [5 7 9 7 7]
 [1 7 5 9 5]
 [4 3 4 8 4]]

sum:  
[[ 9  5 15 12  7]
 [15 17  8 11  6]
 [ 6 13 15 16 11]
 [ 8 12 10 17  7]
 [ 5 11 10 14 12]]

diff:  
[[ 7 -1  1  6  3]
 [ 3  1  4  1  0]
 [-4 -1 -3  2 -3]
 [ 6 -2  0 -1 -3]
 [-3  5  2 -2  4]]

prod:  
[[ 8  6 56 27 10]
 [54 72 12 30  9]
 [ 5 42 54 63 28]
 [ 7 35 25 72 10]
 [ 4 24 24 48 32]]


## 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [10]:
v_1 = np.random.randint(10, size=7)
v_2 = np.random.randint(10, size=7)
print(f"first vector: {v_1}")
print(f"second vector: {v_2}")
print(f"scalar product: {np.dot(v_1, v_2)}")

first vector: [5 9 4 5 2 5 2]
second vector: [9 3 9 3 1 0 8]
scalar product: 141


## 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [11]:
matrix_2x2 = np.random.randint(1,11, size=4).reshape(2,2)
print(f"matrix 2x2: \n{matrix_2x2}\n")
matrix_2x3 = np.random.randint(1,11, size=6).reshape(2,3)
print(f"matrix 2x3: \n{matrix_2x3}\n")
print(np.dot(matrix_2x2, matrix_2x3))

matrix 2x2: 
[[10  7]
 [ 4  4]]

matrix 2x3: 
[[8 6 7]
 [2 1 6]]

[[ 94  67 112]
 [ 40  28  52]]


## 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [12]:
m_3x3_original = np.random.randint(1,11, size=(3,3))
m_3x3_inverted = np.linalg.inv(m_3x3_original)
print(f"original matrix: \n {m_3x3_original} \n")
print(f"inverted: \n {m_3x3_inverted}")

original matrix: 
 [[2 6 6]
 [2 2 3]
 [5 9 3]] 

inverted: 
 [[-0.35        0.6         0.1       ]
 [ 0.15       -0.4         0.1       ]
 [ 0.13333333  0.2        -0.13333333]]


## 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [13]:
mtrx_4x4 = np.random.random((4,4))
print(f"original:\n\n{mtrx_4x4} \n") 
mtrx_4x4_inverted = mtrx_4x4.T
print(f"inverted:\n\n{mtrx_4x4_inverted}")


original:

[[0.36299267 0.70726649 0.76720675 0.0171619 ]
 [0.49589831 0.17223511 0.06649966 0.66363743]
 [0.14675366 0.12240035 0.47981824 0.364611  ]
 [0.63198417 0.16059261 0.56736689 0.70901193]] 

inverted:

[[0.36299267 0.49589831 0.14675366 0.63198417]
 [0.70726649 0.17223511 0.12240035 0.16059261]
 [0.76720675 0.06649966 0.47981824 0.56736689]
 [0.0171619  0.66363743 0.364611   0.70901193]]


## 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [14]:
m_3x4 = np.random.randint(1,11, size=(3,4))
v_4 = np.random.randint(1,10, size=4)
print(f"matrix:\n\n{m_3x4}\n")
print(f"vector:\n\n{v_4}\n")
print(f"product:\n\n{m_3x4 @ v_4}")



matrix:

[[ 8  3  3  6]
 [10  1 10  7]
 [10  1  6  2]]

vector:

[5 3 2 5]

product:

[ 85 108  75]


## 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [15]:
m_2x3 = np.random.random((2,3))
vector_3 = np.random.random(3)
print(m_2x3)
print(vector_3)

[[0.50848426 0.76179546 0.09841573]
 [0.68430105 0.38906569 0.21949415]]
[0.40562242 0.70551753 0.81679321]


## 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [16]:
m_2x2_1 = np.random.randint(1,10, size=4).reshape(2,2)
m_2x2_2 = np.random.randint(1,10, size=4).reshape(2,2)
print(f"first:\n{m_2x2_1}\n")
print(f"second:\n{m_2x2_2}\n")
print(f"product:\n{m_2x2_1 * m_2x2_2}")


first:
[[9 6]
 [6 5]]

second:
[[7 8]
 [9 9]]

product:
[[63 48]
 [54 45]]


## 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [17]:
m2_2x2_1 = np.random.randint(1,10, size=4).reshape(2,2)
m2_2x2_2 = np.random.randint(1,10, size=4).reshape(2,2)
print(f"first:\n{m2_2x2_1}\n")
print(f"second:\n{m2_2x2_2}\n")
print(f"product:\n{np.dot(m2_2x2_1, m2_2x2_2)}")

first:
[[9 1]
 [3 3]]

second:
[[1 8]
 [9 2]]

product:
[[18 74]
 [30 30]]


## 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [18]:
m_5x5 = np.random.randint(1,100, size=25).reshape(5,5)
print(f"matrix:\n{m_5x5}\n")
print(f"sum = {np.sum(m_5x5)}")

matrix:
[[96 60 54 32 50]
 [ 1 33 46 13 30]
 [75 53  1 42 38]
 [77 58 62 66 14]
 [89 29 84 59  5]]

sum = 1167


## 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [19]:
m_diff_1 = np.random.randint(1,10, size=(4,4))
m_diff_2 = np.random.randint(1,10, size=(4,4))
print(f"first:\n{m_diff_1}\n")
print(f"second:\n{m_diff_2}\n")
print(f"diff:\n{m_diff_1 - m_diff_2}")


first:
[[4 2 4 4]
 [8 6 2 6]
 [2 2 1 4]
 [5 9 8 9]]

second:
[[5 4 4 1]
 [5 4 3 8]
 [6 3 5 4]
 [1 4 8 2]]

diff:
[[-1 -2  0  3]
 [ 3  2 -1 -2]
 [-4 -1 -4  0]
 [ 4  5  0  7]]


## 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [20]:
matrix_3x3 = np.random.random((3, 3))
sum_vector = np.sum(matrix_3x3, axis=1).reshape(-1, 1)
print(f"Matrix 3x3:\n{matrix_3x3}\n")
print(f"Sum vector:\n{sum_vector}")

Matrix 3x3:
[[0.07758441 0.5610128  0.7031832 ]
 [0.89737177 0.34985403 0.28868177]
 [0.90920623 0.48497676 0.97069838]]

Sum vector:
[[1.3417804 ]
 [1.53590757]
 [2.36488137]]


## 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створіть матрицю з квадратами цих чисел.

In [21]:
mtrx = np.random.randint(1,10, size=(3,4))
print(f"original:\n{mtrx}\n")
print(f"squared:\n{mtrx ** 2}")


original:
[[4 3 6 3]
 [1 2 6 6]
 [8 3 9 7]]

squared:
[[16  9 36  9]
 [ 1  4 36 36]
 [64  9 81 49]]


## 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [22]:
vect = np.random.randint(1,50, size=4)
print(f"vector:\n{vect}")
print(f"rooted vector:\n{np.sqrt(vect)}")

vector:
[11 18 37 43]
rooted vector:
[3.31662479 4.24264069 6.08276253 6.55743852]
