In [1]:
import numpy as np

## 1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
arr = np.linspace(1,10, num=10,dtype=int)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


## 2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


In [3]:
matrix = np.zeros((3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


## 3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.


In [4]:
matrix_5x5 = np.random.randint(1, 10, size=(5,5))
print(matrix_5x5)

[[3 6 1 1 5]
 [9 8 2 9 8]
 [5 7 5 4 1]
 [9 8 6 9 8]
 [1 2 8 7 5]]


## 4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.


In [5]:
matrix_4x4 = np.random.random((4,4))
print(matrix_4x4)

[[0.71344821 0.99799154 0.7109273  0.54560192]
 [0.97011985 0.10150945 0.74346922 0.27851815]
 [0.36808981 0.5583883  0.32158745 0.38291678]
 [0.54471844 0.8422937  0.51649863 0.14761258]]


## 5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
m5_1 = np.random.randint(1, 10, size=(5,5))
m5_2 = np.random.randint(1, 10, size=(5,5))
mm_sum = m5_1 + m5_2
mm_diff = m5_1 - m5_2
mm_prod = m5_1 * m5_2
print(f"first matrix: \n{m5_1}\n")
print(f"second matrix: \n{m5_2}\n")
print(f"sum:  \n{mm_sum}\n")
print(f"diff:  \n{mm_diff}\n")
print(f"prod:  \n{mm_prod}")

first matrix: 
[[7 8 8 4 6]
 [3 1 2 4 4]
 [4 7 6 4 5]
 [7 1 4 6 3]
 [6 4 1 1 1]]

second matrix: 
[[6 2 3 5 1]
 [2 7 9 2 7]
 [7 7 9 2 6]
 [1 1 5 4 4]
 [3 1 3 3 9]]

sum:  
[[13 10 11  9  7]
 [ 5  8 11  6 11]
 [11 14 15  6 11]
 [ 8  2  9 10  7]
 [ 9  5  4  4 10]]

diff:  
[[ 1  6  5 -1  5]
 [ 1 -6 -7  2 -3]
 [-3  0 -3  2 -1]
 [ 6  0 -1  2 -1]
 [ 3  3 -2 -2 -8]]

prod:  
[[42 16 24 20  6]
 [ 6  7 18  8 28]
 [28 49 54  8 30]
 [ 7  1 20 24 12]
 [18  4  3  3  9]]


## 6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [7]:
v_1 = np.random.randint(10, size=7)
v_2 = np.random.randint(10, size=7)
print(f"first vector: {v_1}")
print(f"second vector: {v_2}")
print(f"scalar product: {np.dot(v_1, v_2)}")

first vector: [8 1 3 2 0 4 9]
second vector: [8 0 5 1 8 7 3]
scalar product: 136


## 7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [8]:
matrix_2x2 = np.random.randint(1,11, size=4).reshape(2,2)
print(f"matrix 2x2: \n{matrix_2x2}\n")
matrix_2x3 = np.random.randint(1,11, size=6).reshape(2,3)
print(f"matrix 2x3: \n{matrix_2x3}\n")
print(np.dot(matrix_2x2, matrix_2x3))

matrix 2x2: 
[[3 1]
 [1 6]]

matrix 2x3: 
[[9 1 5]
 [4 1 6]]

[[31  4 21]
 [33  7 41]]


## 8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [9]:
m_3x3_original = np.random.randint(1,11, size=(3,3))
m_3x3_inverted = np.linalg.inv(m_3x3_original)
print(f"original matrix: \n {m_3x3_original} \n")
print(f"inverted: \n {m_3x3_inverted}")

original matrix: 
 [[ 4  8  4]
 [10  6  1]
 [ 4  7  4]] 

inverted: 
 [[-4.72222222e-01  1.11111111e-01  4.44444444e-01]
 [ 1.00000000e+00 -6.16790569e-18 -1.00000000e+00]
 [-1.27777778e+00 -1.11111111e-01  1.55555556e+00]]


## 9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [10]:
mtrx_4x4 = np.random.random((4,4))
print(f"original:\n\n{mtrx_4x4} \n") 
mtrx_4x4_inverted = mtrx_4x4.T
print(f"inverted:\n\n{mtrx_4x4_inverted}")


original:

[[0.94066605 0.1456988  0.54168568 0.92661337]
 [0.65460844 0.58902232 0.3237066  0.208278  ]
 [0.40214916 0.62228693 0.04567792 0.63341607]
 [0.64255616 0.02037889 0.26336013 0.55668348]] 

inverted:

[[0.94066605 0.65460844 0.40214916 0.64255616]
 [0.1456988  0.58902232 0.62228693 0.02037889]
 [0.54168568 0.3237066  0.04567792 0.26336013]
 [0.92661337 0.208278   0.63341607 0.55668348]]


## 10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [11]:
m_3x4 = np.random.randint(1,11, size=(3,4))
v_4 = np.random.randint(1,10, size=4)
print(f"matrix:\n\n{m_3x4}\n")
print(f"vector:\n\n{v_4}\n")
print(f"product:\n\n{m_3x4 @ v_4}")



matrix:

[[7 9 4 7]
 [3 3 9 4]
 [1 9 5 6]]

vector:

[4 4 3 3]

product:

[97 63 73]


## 11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [12]:
m_2x3 = np.random.random((2,3))
vector_3 = np.random.random(3)
print(m_2x3)
print(vector_3)

[[0.53513807 0.21804086 0.13552571]
 [0.64516511 0.74538393 0.3180103 ]]
[0.14069182 0.85322199 0.27406481]


## 12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [13]:
m_2x2_1 = np.random.randint(1,10, size=4).reshape(2,2)
m_2x2_2 = np.random.randint(1,10, size=4).reshape(2,2)
print(f"first:\n{m_2x2_1}\n")
print(f"second:\n{m_2x2_2}\n")
print(f"product:\n{m_2x2_1 * m_2x2_2}")


first:
[[6 7]
 [8 3]]

second:
[[9 8]
 [5 5]]

product:
[[54 56]
 [40 15]]


## 13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [14]:
m2_2x2_1 = np.random.randint(1,10, size=4).reshape(2,2)
m2_2x2_2 = np.random.randint(1,10, size=4).reshape(2,2)
print(f"first:\n{m2_2x2_1}\n")
print(f"second:\n{m2_2x2_2}\n")
print(f"product:\n{np.dot(m2_2x2_1, m2_2x2_2)}")

first:
[[3 9]
 [2 6]]

second:
[[9 6]
 [1 1]]

product:
[[36 27]
 [24 18]]


## 14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [15]:
m_5x5 = np.random.randint(1,100, size=25).reshape(5,5)
print(f"matrix:\n{m_5x5}\n")
print(f"sum = {np.sum(m_5x5)}")

matrix:
[[96  6 82 16 54]
 [85 35 25  5 94]
 [36 64  2 20 43]
 [89 59 42 61 52]
 [58 76 96 76 36]]

sum = 1308


## 15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [16]:
m_diff_1 = np.random.randint(1,10, size=(4,4))
m_diff_2 = np.random.randint(1,10, size=(4,4))
print(f"first:\n{m_diff_1}\n")
print(f"second:\n{m_diff_2}\n")
print(f"diff:\n{m_diff_1 - m_diff_2}")


first:
[[2 3 3 1]
 [6 9 3 5]
 [2 4 4 4]
 [2 5 8 1]]

second:
[[8 6 2 1]
 [1 6 7 8]
 [3 9 1 9]
 [1 6 2 1]]

diff:
[[-6 -3  1  0]
 [ 5  3 -4 -3]
 [-1 -5  3 -5]
 [ 1 -1  6  0]]


## 16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [17]:
matrix_3x3 = np.random.random((3, 3))
sum_vector = np.sum(matrix_3x3, axis=1).reshape(-1, 1)
print(f"Matrix 3x3:\n{matrix_3x3}\n")
print(f"Sum vector:\n{sum_vector}")

Matrix 3x3:
[[0.11858545 0.45447877 0.06457167]
 [0.96496752 0.17274906 0.2382866 ]
 [0.7428483  0.30800238 0.10790815]]

Sum vector:
[[0.63763589]
 [1.37600318]
 [1.15875883]]


## 17. Створіть матрицю розміром 3x4 з довільними цілими числами і створіть матрицю з квадратами цих чисел.

In [18]:
mtrx = np.random.randint(1,10, size=(3,4))
print(f"original:\n{mtrx}\n")
print(f"squared:\n{mtrx ** 2}")


original:
[[7 4 6 5]
 [4 2 2 7]
 [5 4 3 6]]

squared:
[[49 16 36 25]
 [16  4  4 49]
 [25 16  9 36]]


## 18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [19]:
vect = np.random.randint(1,50, size=4)
print(f"vector:\n{vect}")
print(f"rooted vector:\n{np.sqrt(vect)}")

vector:
[ 7 16 28 35]
rooted vector:
[2.64575131 4.         5.29150262 5.91607978]
